declare const styles: {
  readonly 'layout-container': string;
  readonly 'scroll-wrapper': string;
  readonly 'scroll-wrapper-scrollable': string;
  readonly 'layout-header': string;
  readonly 'layout-header-base': string;
  readonly 'layout-header-fixed': string;
  readonly 'layout-header-placement': string;
  readonly 'layout-tab': string;
  readonly 'layout-tab-base': string;
  readonly 'layout-tab-fixed': string;
  readonly 'layout-tab-top': string;
  readonly 'layout-tab-placement': string;
  readonly 'layout-sider': string;
  readonly 'layout-sider-base': string;
  readonly 'layout-mobile-sider': string;
  readonly 'layout-mobile-sider-base': string;
  readonly 'layout-mobile-sider-hidden': string;
  readonly 'layout-mobile-sider-mask': string;
  readonly 'layout-mobile-sider-mask-base': string;
  readonly 'layout-sider_collapsed': string;
  readonly 'layout-content': string;
  readonly 'layout-content-scrollable': string;
  readonly 'layout-footer': string;
  readonly 'layout-footer-base': string;
  readonly 'layout-footer-fixed': string;
  readonly 'layout-footer-placement': string;
  readonly 'left-gap': string;
  readonly 'left-gap_collapsed': string;
  readonly 'sider-padding-top': string;
  readonly 'sider-padding-bottom': string;
};

export default styles;
